# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mawin.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import (QLabel, QMessageBox)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 702)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -3803, 1400, 4427))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout.addWidget(self.lineEdit_3)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout.addWidget(self.lineEdit_4)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout.addWidget(self.lineEdit_5)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout.addWidget(self.lineEdit_6)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.verticalLayout.addWidget(self.lineEdit_7)
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.verticalLayout.addWidget(self.lineEdit_8)
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.verticalLayout.addWidget(self.lineEdit_9)
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_14.setObjectName("label_14")
        self.verticalLayout.addWidget(self.label_14)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.verticalLayout.addWidget(self.lineEdit_10)
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_15.setObjectName("label_15")
        self.verticalLayout.addWidget(self.label_15)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.verticalLayout.addWidget(self.lineEdit_11)
        self.label_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_16.setObjectName("label_16")
        self.verticalLayout.addWidget(self.label_16)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.verticalLayout.addWidget(self.lineEdit_12)
        self.label_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.verticalLayout.addWidget(self.label_17)
        self.label_24 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.verticalLayout.addWidget(self.label_24)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.verticalLayout.addWidget(self.lineEdit_13)
        self.label_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_18.setObjectName("label_18")
        self.verticalLayout.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_19.setObjectName("label_19")
        self.verticalLayout.addWidget(self.label_19)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.verticalLayout.addWidget(self.lineEdit_14)
        self.label_20 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_20.setObjectName("label_20")
        self.verticalLayout.addWidget(self.label_20)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.verticalLayout.addWidget(self.lineEdit_15)
        self.label_21 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_21.setObjectName("label_21")
        self.verticalLayout.addWidget(self.label_21)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.verticalLayout.addWidget(self.lineEdit_16)
        self.label_22 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.verticalLayout.addWidget(self.label_22)
        self.label_23 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_23.setObjectName("label_23")
        self.verticalLayout.addWidget(self.label_23)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.verticalLayout.addWidget(self.lineEdit_17)
        self.label_25 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.verticalLayout.addWidget(self.label_25)
        self.label_30 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_30.setObjectName("label_30")
        self.verticalLayout.addWidget(self.label_30)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.verticalLayout.addWidget(self.lineEdit_18)
        self.label_29 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_29.setObjectName("label_29")
        self.verticalLayout.addWidget(self.label_29)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.verticalLayout.addWidget(self.lineEdit_19)
        self.label_28 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_28.setObjectName("label_28")
        self.verticalLayout.addWidget(self.label_28)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.verticalLayout.addWidget(self.lineEdit_20)
        self.label_27 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_27.setObjectName("label_27")
        self.verticalLayout.addWidget(self.label_27)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.verticalLayout.addWidget(self.lineEdit_21)
        self.label_26 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_26.setObjectName("label_26")
        self.verticalLayout.addWidget(self.label_26)
        self.lineEdit_22 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.verticalLayout.addWidget(self.lineEdit_22)
        self.label_32 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_32.setObjectName("label_32")
        self.verticalLayout.addWidget(self.label_32)
        self.lineEdit_23 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.verticalLayout.addWidget(self.lineEdit_23)
        self.label_43 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_43.setObjectName("label_43")
        self.verticalLayout.addWidget(self.label_43)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.verticalLayout.addWidget(self.lineEdit_24)
        self.label_42 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_42.setObjectName("label_42")
        self.verticalLayout.addWidget(self.label_42)
        self.lineEdit_25 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.verticalLayout.addWidget(self.lineEdit_25)
        self.label_41 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_41.setObjectName("label_41")
        self.verticalLayout.addWidget(self.label_41)
        self.lineEdit_26 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.verticalLayout.addWidget(self.lineEdit_26)
        self.label_40 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_40.setObjectName("label_40")
        self.verticalLayout.addWidget(self.label_40)
        self.lineEdit_27 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.verticalLayout.addWidget(self.lineEdit_27)
        self.label_39 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.verticalLayout.addWidget(self.label_39)
        self.label_38 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_38.setObjectName("label_38")
        self.verticalLayout.addWidget(self.label_38)
        self.lineEdit_28 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.verticalLayout.addWidget(self.lineEdit_28)
        self.label_37 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_37.setObjectName("label_37")
        self.verticalLayout.addWidget(self.label_37)
        self.lineEdit_29 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.verticalLayout.addWidget(self.lineEdit_29)
        self.label_36 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_36.setObjectName("label_36")
        self.verticalLayout.addWidget(self.label_36)
        self.lineEdit_30 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.verticalLayout.addWidget(self.lineEdit_30)
        self.label_35 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_35.setObjectName("label_35")
        self.verticalLayout.addWidget(self.label_35)
        self.lineEdit_31 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.verticalLayout.addWidget(self.lineEdit_31)
        self.label_34 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_34.setObjectName("label_34")
        self.verticalLayout.addWidget(self.label_34)
        self.lineEdit_32 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.verticalLayout.addWidget(self.lineEdit_32)
        self.label_33 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_33.setObjectName("label_33")
        self.verticalLayout.addWidget(self.label_33)
        self.lineEdit_33 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.verticalLayout.addWidget(self.lineEdit_33)
        self.label_53 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_53.setObjectName("label_53")
        self.verticalLayout.addWidget(self.label_53)
        self.lineEdit_34 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.verticalLayout.addWidget(self.lineEdit_34)
        self.label_45 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_45.setObjectName("label_45")
        self.verticalLayout.addWidget(self.label_45)
        self.lineEdit_35 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.verticalLayout.addWidget(self.lineEdit_35)
        self.label_52 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_52.setObjectName("label_52")
        self.verticalLayout.addWidget(self.label_52)
        self.lineEdit_36 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.verticalLayout.addWidget(self.lineEdit_36)
        self.label_51 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_51.setObjectName("label_51")
        self.verticalLayout.addWidget(self.label_51)
        self.lineEdit_37 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.verticalLayout.addWidget(self.lineEdit_37)
        self.label_50 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.verticalLayout.addWidget(self.label_50)
        self.lineEdit_38 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.verticalLayout.addWidget(self.lineEdit_38)
        self.label_54 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.verticalLayout.addWidget(self.label_54)
        self.label_56 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_56.setFont(font)
        self.label_56.setObjectName("label_56")
        self.verticalLayout.addWidget(self.label_56)
        self.label_57 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_57.setObjectName("label_57")
        self.verticalLayout.addWidget(self.label_57)
        self.lineEdit_39 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.verticalLayout.addWidget(self.lineEdit_39)
        self.label_55 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_55.setObjectName("label_55")
        self.verticalLayout.addWidget(self.label_55)
        self.lineEdit_40 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.verticalLayout.addWidget(self.lineEdit_40)
        self.label_49 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_49.setObjectName("label_49")
        self.verticalLayout.addWidget(self.label_49)
        self.lineEdit_41 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.verticalLayout.addWidget(self.lineEdit_41)
        self.label_48 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_48.setObjectName("label_48")
        self.verticalLayout.addWidget(self.label_48)
        self.lineEdit_42 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.verticalLayout.addWidget(self.lineEdit_42)
        self.label_47 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_47.setObjectName("label_47")
        self.verticalLayout.addWidget(self.label_47)
        self.lineEdit_43 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.verticalLayout.addWidget(self.lineEdit_43)
        self.label_46 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_46.setObjectName("label_46")
        self.verticalLayout.addWidget(self.label_46)
        self.lineEdit_44 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_44.setObjectName("lineEdit_44")
        self.verticalLayout.addWidget(self.lineEdit_44)
        self.label_44 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_44.setObjectName("label_44")
        self.verticalLayout.addWidget(self.label_44)
        self.lineEdit_45 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_45.setObjectName("lineEdit_45")
        self.verticalLayout.addWidget(self.lineEdit_45)
        self.label_71 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_71.setObjectName("label_71")
        self.verticalLayout.addWidget(self.label_71)
        self.lineEdit_46 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_46.setObjectName("lineEdit_46")
        self.verticalLayout.addWidget(self.lineEdit_46)
        self.label_72 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_72.setObjectName("label_72")
        self.verticalLayout.addWidget(self.label_72)
        self.lineEdit_47 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_47.setObjectName("lineEdit_47")
        self.verticalLayout.addWidget(self.lineEdit_47)
        self.label_70 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_70.setObjectName("label_70")
        self.verticalLayout.addWidget(self.label_70)
        self.lineEdit_48 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_48.setObjectName("lineEdit_48")
        self.verticalLayout.addWidget(self.lineEdit_48)
        self.label_68 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_68.setFont(font)
        self.label_68.setObjectName("label_68")
        self.verticalLayout.addWidget(self.label_68)
        self.label_79 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_79.setObjectName("label_79")
        self.verticalLayout.addWidget(self.label_79)
        self.lineEdit_49 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_49.setObjectName("lineEdit_49")
        self.verticalLayout.addWidget(self.lineEdit_49)
        self.label_78 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_78.setObjectName("label_78")
        self.verticalLayout.addWidget(self.label_78)
        self.lineEdit_50 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_50.setObjectName("lineEdit_50")
        self.verticalLayout.addWidget(self.lineEdit_50)
        self.label_80 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_80.setObjectName("label_80")
        self.verticalLayout.addWidget(self.label_80)
        self.lineEdit_51 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_51.setObjectName("lineEdit_51")
        self.verticalLayout.addWidget(self.lineEdit_51)
        self.label_69 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_69.setFont(font)
        self.label_69.setObjectName("label_69")
        self.verticalLayout.addWidget(self.label_69)
        self.label_77 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_77.setObjectName("label_77")
        self.verticalLayout.addWidget(self.label_77)
        self.lineEdit_52 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_52.setObjectName("lineEdit_52")
        self.verticalLayout.addWidget(self.lineEdit_52)
        self.label_74 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_74.setObjectName("label_74")
        self.verticalLayout.addWidget(self.label_74)
        self.lineEdit_53 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_53.setObjectName("lineEdit_53")
        self.verticalLayout.addWidget(self.lineEdit_53)
        self.label_75 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_75.setObjectName("label_75")
        self.verticalLayout.addWidget(self.label_75)
        self.lineEdit_54 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_54.setObjectName("lineEdit_54")
        self.verticalLayout.addWidget(self.lineEdit_54)
        self.label_76 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_76.setObjectName("label_76")
        self.verticalLayout.addWidget(self.label_76)
        self.lineEdit_55 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_55.setObjectName("lineEdit_55")
        self.verticalLayout.addWidget(self.lineEdit_55)
        self.label_66 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_66.setObjectName("label_66")
        self.verticalLayout.addWidget(self.label_66)
        self.lineEdit_56 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_56.setObjectName("lineEdit_56")
        self.verticalLayout.addWidget(self.lineEdit_56)
        self.label_67 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_67.setObjectName("label_67")
        self.verticalLayout.addWidget(self.label_67)
        self.lineEdit_57 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_57.setObjectName("lineEdit_57")
        self.verticalLayout.addWidget(self.lineEdit_57)
        self.label_65 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_65.setObjectName("label_65")
        self.verticalLayout.addWidget(self.label_65)
        self.lineEdit_58 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_58.setObjectName("lineEdit_58")
        self.verticalLayout.addWidget(self.lineEdit_58)
        self.label_64 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_64.setObjectName("label_64")
        self.verticalLayout.addWidget(self.label_64)
        self.lineEdit_59 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_59.setObjectName("lineEdit_59")
        self.verticalLayout.addWidget(self.lineEdit_59)
        self.label_73 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_73.setFont(font)
        self.label_73.setObjectName("label_73")
        self.verticalLayout.addWidget(self.label_73)
        self.label_63 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_63.setObjectName("label_63")
        self.verticalLayout.addWidget(self.label_63)
        self.lineEdit_60 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_60.setObjectName("lineEdit_60")
        self.verticalLayout.addWidget(self.lineEdit_60)
        self.label_62 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_62.setObjectName("label_62")
        self.verticalLayout.addWidget(self.label_62)
        self.lineEdit_61 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_61.setObjectName("lineEdit_61")
        self.verticalLayout.addWidget(self.lineEdit_61)
        self.label_61 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_61.setObjectName("label_61")
        self.verticalLayout.addWidget(self.label_61)
        self.lineEdit_62 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_62.setObjectName("lineEdit_62")
        self.verticalLayout.addWidget(self.lineEdit_62)
        self.label_60 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_60.setObjectName("label_60")
        self.verticalLayout.addWidget(self.label_60)
        self.lineEdit_63 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_63.setObjectName("lineEdit_63")
        self.verticalLayout.addWidget(self.lineEdit_63)
        self.label_59 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_59.setObjectName("label_59")
        self.verticalLayout.addWidget(self.label_59)
        self.lineEdit_64 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_64.setObjectName("lineEdit_64")
        self.verticalLayout.addWidget(self.lineEdit_64)
        self.label_58 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_58.setObjectName("label_58")
        self.verticalLayout.addWidget(self.label_58)
        self.lineEdit_65 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_65.setObjectName("lineEdit_65")
        self.verticalLayout.addWidget(self.lineEdit_65)
        self.label_81 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_81.setObjectName("label_81")
        self.verticalLayout.addWidget(self.label_81)
        self.lineEdit_66 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_66.setObjectName("lineEdit_66")
        self.verticalLayout.addWidget(self.lineEdit_66)
        self.label_88 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_88.setObjectName("label_88")
        self.verticalLayout.addWidget(self.label_88)
        self.lineEdit_67 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_67.setObjectName("lineEdit_67")
        self.verticalLayout.addWidget(self.lineEdit_67)
        self.label_94 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_94.setObjectName("label_94")
        self.verticalLayout.addWidget(self.label_94)
        self.lineEdit_68 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_68.setObjectName("lineEdit_68")
        self.verticalLayout.addWidget(self.lineEdit_68)
        self.label_92 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_92.setObjectName("label_92")
        self.verticalLayout.addWidget(self.label_92)
        self.lineEdit_69 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_69.setObjectName("lineEdit_69")
        self.verticalLayout.addWidget(self.lineEdit_69)
        self.label_91 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_91.setObjectName("label_91")
        self.verticalLayout.addWidget(self.label_91)
        self.lineEdit_70 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_70.setObjectName("lineEdit_70")
        self.verticalLayout.addWidget(self.lineEdit_70)
        self.label_85 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_85.setObjectName("label_85")
        self.verticalLayout.addWidget(self.label_85)
        self.lineEdit_71 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_71.setObjectName("lineEdit_71")
        self.verticalLayout.addWidget(self.lineEdit_71)
        self.label_93 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_93.setObjectName("label_93")
        self.verticalLayout.addWidget(self.label_93)
        self.lineEdit_72 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_72.setObjectName("lineEdit_72")
        self.verticalLayout.addWidget(self.lineEdit_72)
        self.label_89 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_89.setFont(font)
        self.label_89.setObjectName("label_89")
        self.verticalLayout.addWidget(self.label_89)
        self.label_87 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_87.setObjectName("label_87")
        self.verticalLayout.addWidget(self.label_87)
        self.lineEdit_73 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_73.setObjectName("lineEdit_73")
        self.verticalLayout.addWidget(self.lineEdit_73)
        self.label_90 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_90.setObjectName("label_90")
        self.verticalLayout.addWidget(self.label_90)
        self.lineEdit_74 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_74.setObjectName("lineEdit_74")
        self.verticalLayout.addWidget(self.lineEdit_74)
        self.label_84 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_84.setObjectName("label_84")
        self.verticalLayout.addWidget(self.label_84)
        self.lineEdit_75 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_75.setObjectName("lineEdit_75")
        self.verticalLayout.addWidget(self.lineEdit_75)
        self.label_83 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_83.setObjectName("label_83")
        self.verticalLayout.addWidget(self.label_83)
        self.lineEdit_76 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_76.setObjectName("lineEdit_76")
        self.verticalLayout.addWidget(self.lineEdit_76)
        self.label_97 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_97.setObjectName("label_97")
        self.verticalLayout.addWidget(self.label_97)
        self.lineEdit_77 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_77.setObjectName("lineEdit_77")
        self.verticalLayout.addWidget(self.lineEdit_77)
        self.label_99 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_99.setObjectName("label_99")
        self.verticalLayout.addWidget(self.label_99)
        self.lineEdit_78 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_78.setObjectName("lineEdit_78")
        self.verticalLayout.addWidget(self.lineEdit_78)
        self.label_98 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_98.setObjectName("label_98")
        self.verticalLayout.addWidget(self.label_98)
        self.lineEdit_79 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_79.setObjectName("lineEdit_79")
        self.verticalLayout.addWidget(self.lineEdit_79)
        self.label_100 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_100.setObjectName("label_100")
        self.verticalLayout.addWidget(self.label_100)
        self.lineEdit_80 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_80.setObjectName("lineEdit_80")
        self.verticalLayout.addWidget(self.lineEdit_80)
        self.label_86 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_86.setObjectName("label_86")
        self.verticalLayout.addWidget(self.label_86)
        self.lineEdit_81 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_81.setObjectName("lineEdit_81")
        self.verticalLayout.addWidget(self.lineEdit_81)
        self.label_96 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_96.setObjectName("label_96")
        self.verticalLayout.addWidget(self.label_96)
        self.lineEdit_82 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_82.setObjectName("lineEdit_82")
        self.verticalLayout.addWidget(self.lineEdit_82)
        self.label_95 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_95.setObjectName("label_95")
        self.verticalLayout.addWidget(self.label_95)
        self.lineEdit_83 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_83.setObjectName("lineEdit_83")
        self.verticalLayout.addWidget(self.lineEdit_83)
        self.label_82 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_82.setObjectName("label_82")
        self.verticalLayout.addWidget(self.label_82)
        self.lineEdit_84 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_84.setObjectName("lineEdit_84")
        self.verticalLayout.addWidget(self.lineEdit_84)
        self.label_31 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_31.setObjectName("label_31")
        self.verticalLayout.addWidget(self.label_31)
        self.lineEdit_85 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_85.setObjectName("lineEdit_85")
        self.verticalLayout.addWidget(self.lineEdit_85)
        self.label_101 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_101.setObjectName("label_101")
        self.verticalLayout.addWidget(self.label_101)
        self.lineEdit_86 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_86.setObjectName("lineEdit_86")
        self.verticalLayout.addWidget(self.lineEdit_86)
        self.label_102 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_102.setFont(font)
        self.label_102.setObjectName("label_102")
        self.verticalLayout.addWidget(self.label_102)
        self.lineEdit_87 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_87.setObjectName("lineEdit_87")
        self.verticalLayout.addWidget(self.lineEdit_87)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton.setAutoFillBackground(False)
        icon = QtGui.QIcon.fromTheme("plastique")
        self.pushButton.setIcon(icon)
        self.pushButton.setAutoDefault(False)
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        #self.pushButton.clicked.connect(self.savequestion)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def savequestion(self,event):
        reply = QMessageBox.question(self,'Message','Are you Sure?', QMessageBox.Yes | QMessageBox.No, QMessageBox.No)
        if reply == QMessageBox.Yes:
            event.exept()
        else:
            event.ignore()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "1. Основные характеристики."))
        self.label_2.setText(_translate("MainWindow", "1.1 Вид объекта нежвижимости:                             "))
        self.label_3.setText(_translate("MainWindow", "1.2 Кадастровый номер объекта недвижимости:"))
        self.label_4.setText(_translate("MainWindow", "2. Сведения о собственнике."))
        self.label_5.setText(_translate("MainWindow", "2.1 Фамилия, имя, отчество физического лица (последнее - при наличии),наименование юридического лица:"))
        self.label_6.setText(_translate("MainWindow", "2.2 Почтовый адрес:                                                 "))
        self.label_7.setText(_translate("MainWindow", "2.3 Адрес электронной почты, телефон:               "))
        self.label_8.setText(_translate("MainWindow", "3. Сведения о заявителе."))
        self.label_9.setText(_translate("MainWindow", "3.1 Фамилия, имя, отчество физического лица (последнее - при наличии), наименование юридического лица: "))
        self.label_10.setText(_translate("MainWindow", "3.2 Почтовый адрес:                                                 "))
        self.label_11.setText(_translate("MainWindow", "3.3 Адрес электронной почты, телефон:"))
        self.label_12.setText(_translate("MainWindow", "4. Сведения о представителе заявителя."))
        self.label_13.setText(_translate("MainWindow", "4.1 Фамилия, имя, отчество физического лица (последнее - при наличии),\n"
" наименование юридического лица: "))
        self.label_14.setText(_translate("MainWindow", "4.2 Реквизиты (номер и дата) документа, удостоверяющего полномочия представителя:"))
        self.label_15.setText(_translate("MainWindow", "4.3 Почтовый адрес:"))
        self.label_16.setText(_translate("MainWindow", "4.4 Адрес электронной почты, телефон:"))
        self.label_17.setText(_translate("MainWindow", "5. Сведения о характеристиках земельного участка. "))
        self.label_24.setText(_translate("MainWindow", "5.1 Основные характеристики"))
        self.label_18.setText(_translate("MainWindow", "5.1.1 Категория земель:"))
        self.label_19.setText(_translate("MainWindow", "5.1.2 Вид разрешенного использования:"))
        self.label_20.setText(_translate("MainWindow", "5.1.3 Адрес:"))
        self.label_21.setText(_translate("MainWindow", "5.1.4 Описание местоположения:"))
        self.label_22.setText(_translate("MainWindow", "5.2 Количественные характеристики"))
        self.label_23.setText(_translate("MainWindow", "5.2.1 Площадь:"))
        self.label_25.setText(_translate("MainWindow", "5.3 Качественные характеристики"))
        self.label_30.setText(_translate("MainWindow", "5.3.1 Фактическое использование:"))
        self.label_29.setText(_translate("MainWindow", "5.3.2 Сведения о лесах, водных объектах и об иных природных объектах, расположенных в пределах земельного участка:"))
        self.label_28.setText(_translate("MainWindow", "5.3.3 Сведения о том, что земельный участок полностью или частично расположен в границах зоны с особыми условиями использования территории или территорий,\n"
" на которых расположены объекты культурного наследия (памятники истории и культуры) народов Российской Федерации, включая ограничения по использованию земельного участка, \n"
"установленные для такой зоны или территории:"))
        self.label_27.setText(_translate("MainWindow", "5.3.4 Сведения о том, что земельный участок расположен в границах особо охраняемой природной территории, охотничьих угодий, лесничеств, лесопарков:"))
        self.label_26.setText(_translate("MainWindow", "5.3.5 Расположение земельного участка (в том числе удаленность земельного участка) относительно автомобильных дорог федерального, регионального или межмуниципального, местного значения, частных автомобильных дорог, их наименование:"))
        self.label_32.setText(_translate("MainWindow", "5.3.6 Тип покрытия (асфальт, бетон, улучшенное грунтовое покрытие, грунтовое покрытие, без покрытия и прочее) подъездного пути к земельному участку (в том числе удаленность земельного участка):"))
        self.label_43.setText(_translate("MainWindow", "5.3.7 Расположение земельного участка (в том числе удаленность земельного участка) относительно водных объектов (море, река, озеро, пруд, затопленный карьер и прочее) их наименование и тип:"))
        self.label_42.setText(_translate("MainWindow", "5.3.8 Расположение земельного участка (в том числе удаленность земельного участка) относительно рекреационной зоны (лесной массив, парковая зона, заповедная зона и прочее), ее наименование и тип:"))
        self.label_41.setText(_translate("MainWindow", "5.3.9 Сведения о вхождении земельного участка в состав единого недвижимого комплекса (ЕНК) или предприятия как имущественного комплекса (в том числе кадастровый номер ЕНК, предприятия как имущественного комплекса):"))
        self.label_40.setText(_translate("MainWindow", "5.3.10 Описание коммуникаций (электроснабжение, газоснабжение, водоснабжение, теплоснабжение, канализация), в том числе их удаленность от земельного участка:"))
        self.label_39.setText(_translate("MainWindow", "5.4 Характеристики зданий, сооружений, объектов незавершенного строительства, расположенных на земельном участке"))
        self.label_38.setText(_translate("MainWindow", "5.4.1 Вид объекта недвижимости:"))
        self.label_37.setText(_translate("MainWindow", "5.4.2 Кадастровый номер:"))
        self.label_36.setText(_translate("MainWindow", "5.4.3 Назначение здания (нежилое, жилое, многоквартирный дом, жилое строение), помещения (жилое (квартира, комната), нежилое), ЕНК, предприятия как имущественного комплекса, объекта незавершенного строительства, иного вида объекта недвижимости:"))
        self.label_35.setText(_translate("MainWindow", "5.4.4 Наименование зданий, сооружений:"))
        self.label_34.setText(_translate("MainWindow", "5.4.5 Вид разрешенного использования зданий, сооружений:"))
        self.label_33.setText(_translate("MainWindow", "5.4.6 Площадь зданий, сооружений:"))
        self.label_53.setText(_translate("MainWindow", "5.4.7 Количество этажей, в том числе подземных этажей, зданий или сооружений (при наличии этажности у зданий или сооружений):"))
        self.label_45.setText(_translate("MainWindow", "5.4.8 Материал наружных стен зданий, сооружений, объектов незавершенного строительства:"))
        self.label_52.setText(_translate("MainWindow", "5.4.9 Год ввода в эксплуатацию расположенных на земельном участке зданий или сооружений по завершении их строительства либо год завершения строительства таких объектов недвижимости, если в соответствии с федеральным законом \n"
"выдача разрешения на ввод объекта в эксплуатацию для зданий или сооружений не предусматривается:"))
        self.label_51.setText(_translate("MainWindow", "5.4.10 Дата окончания проведения капитального ремонта (реконструкции) зданий, сооружений:"))
        self.label_50.setText(_translate("MainWindow", "5.5 Иное:"))
        self.label_54.setText(_translate("MainWindow", "6. Сведения о характеристиках здания, сооружения, помещения, машино-места, объекта незавершенного строительства, единого недвижимого комплекса, \n"
"предприятия как имущественного комплекса, иного вида объектов недвижимости"))
        self.label_56.setText(_translate("MainWindow", "6.1 Основные характеристики"))
        self.label_57.setText(_translate("MainWindow", "6.1.1 Назначение здания (нежилое, жилое, многоквартирный дом, жилое строение), помещения (жилое (квартира, комната), нежилое), ЕНК, предприятия как имущественного комплекса, объекта незавершенного строительства, иного вида объекта недвижимости:"))
        self.label_55.setText(_translate("MainWindow", "6.1.2 Вид разрешенного использования, если объектом недвижимости является здание, сооружение, помещение:"))
        self.label_49.setText(_translate("MainWindow", "6.1.3 Адрес:"))
        self.label_48.setText(_translate("MainWindow", "6.1.4 Описание местоположения:"))
        self.label_47.setText(_translate("MainWindow", "6.1.5 Кадастровые номера помещений, машино-мест, расположенных в здании или сооружении, если объектом недвижимости является здание или сооружение:"))
        self.label_46.setText(_translate("MainWindow", "6.1.6 Кадастровые номера земельных участков, в пределах которых расположены здание, помещение, машино-место, сооружение, объект незавершенного строительства, ЕНК, предприятие как имущественный комплекс, иной вид объекта недвижимости:"))
        self.label_44.setText(_translate("MainWindow", "6.1.7 Кадастровый номер квартиры, в которой расположена комната, если объектом недвижимости является комната:"))
        self.label_71.setText(_translate("MainWindow", "6.1.8 Сведения о вхождении здания, сооружения, помещения, машино-места, объекта незавершенного строительства в состав ЕНК или предприятия как имущественного комплекса (в том числе кадастровый номер ЕНК, предприятия как имущественного комплекса), \n"
"если объектом недвижимости является здание, сооружение, помещение, машино-место, объект незавершенного строительства:"))
        self.label_72.setText(_translate("MainWindow", "6.1.9 Кадастровые номера объектов недвижимости, входящих в состав ЕНК, если объектом недвижимости является единый недвижимый комплекс или кадастровые номера объектов недвижимости, входящих в состав предприятия как имущественного комплекса, \n"
"если объектом недвижимости является предприятие как имущественный комплекс и в его состав входят объекты недвижимости:"))
        self.label_70.setText(_translate("MainWindow", "6.1.10 Сведения о включении объекта недвижимости в единый государственный реестр объектов культурного наследия (памятников истории и культуры) народов Российской Федерации:"))
        self.label_68.setText(_translate("MainWindow", "6.2 Количественные характеристики"))
        self.label_79.setText(_translate("MainWindow", "6.2.1 Площадь (здания, помещения, машино-места, сооружения), основная характеристика (сооружения), проектируемая основная характеристика (объект незавершенного строительства):"))
        self.label_78.setText(_translate("MainWindow", "6.2.2 Количество этажей, в том числе подземных этажей, если объектом недвижимости является здание или сооружение (при наличии этажности у здания или сооружения):"))
        self.label_80.setText(_translate("MainWindow", "6.2.3 Номер этажа здания или сооружения, на котором расположено помещение или машино-место, для помещений или машино-мест:"))
        self.label_69.setText(_translate("MainWindow", "6.3 Качественные характеристики"))
        self.label_77.setText(_translate("MainWindow", "6.3.1 Фактическое использование:"))
        self.label_74.setText(_translate("MainWindow", "6.3.2 Наименование, если объектом недвижимости являются здания, сооружения, помещения, машино-место, ЕНК, предприятие как имущественный комплекс:"))
        self.label_75.setText(_translate("MainWindow", "6.3.3 Материал наружных стен, если объектом недвижимости является здание, сооружение, объект незавершенного строительства:"))
        self.label_76.setText(_translate("MainWindow", "6.3.4 Год ввода в эксплуатацию здания или сооружения по завершении его строительства либо год завершения строительства таких объектов недвижимости, если в соответствии с федеральным законом \n"
"выдача разрешения на ввод объекта в эксплуатацию не предусматривается, если объектом недвижимости является здание или сооружение:"))
        self.label_66.setText(_translate("MainWindow", "6.3.5 Дата окончания проведения капитального ремонта (реконструкции), если объектом недвижимости является здание или сооружение:"))
        self.label_67.setText(_translate("MainWindow", "6.3.6 Сведения о том, что помещение предназначено для обслуживания всех остальных помещений и (или) машино-мест в здании, сооружении или о том, что такое помещение относится к имуществу общего пользования в многоквартирном доме, \n"
"если объектом недвижимости является помещение:"))
        self.label_65.setText(_translate("MainWindow", "6.3.7 Линия застройки, если объектом недвижимости является здание, сооружение или объект незавершенного строительства:"))
        self.label_64.setText(_translate("MainWindow", "6.3.8 Наличие коммуникаций (электроснабжение, газоснабжение, водоснабжение, теплоснабжение, канализация):"))
        self.label_73.setText(_translate("MainWindow", "6.4. Характеристики земельных участков, на которых расположено здание, сооружение, объект незавершенного строительства, \n"
"единый недвижимый комплекс, предприятие как имущественный комплекс, иной вид объекта недвижимости:"))
        self.label_63.setText(_translate("MainWindow", "6.4.1 Кадастровый номер:"))
        self.label_62.setText(_translate("MainWindow", "6.4.2 Категория земель:"))
        self.label_61.setText(_translate("MainWindow", "6.4.3 Вид разрешенного использования:"))
        self.label_60.setText(_translate("MainWindow", "6.4.4 Площадь:"))
        self.label_59.setText(_translate("MainWindow", "6.4.5 Фактическое использование:"))
        self.label_58.setText(_translate("MainWindow", "6.4.6 Сведения о лесах, водных объектах и об иных природных объектах, расположенных в пределах земельного участка:"))
        self.label_81.setText(_translate("MainWindow", "6.4.7 Сведения о том, что земельный участок полностью или частично расположен в границах зоны с особыми условиями использования территории или территорий, на которых расположены объекты культурного наследия (памятники истории и культуры) \n"
"народов Российской Федерации, включая ограничения по использованию земельного участка, установленные для такой зоны или территории:"))
        self.label_88.setText(_translate("MainWindow", "6.4.8 Сведения о том, что земельный участок расположен в границах особо охраняемой природной территории, охотничьих угодий, лесничеств, лесопарков:"))
        self.label_94.setText(_translate("MainWindow", "6.4.9 Расположение земельного участка (в том числе удаленность земельного участка) относительно автомобильных дорог федерального, регионального или межмуниципального, местного значения, частных автомобильных дорог, их наименование:"))
        self.label_92.setText(_translate("MainWindow", "6.4.10 Тип покрытия (асфальт, бетон, улучшенное грунтовое покрытие, грунтовое покрытие, без покрытия и прочее) подъездного пути к земельному участку (в том числе удаленность земельного участка):"))
        self.label_91.setText(_translate("MainWindow", "6.4.11 Расположение земельного участка (в том числе удаленность земельного участка) относительно водных объектов (море, река, озеро, пруд, затопленный карьер и прочее), их наименование и тип:"))
        self.label_85.setText(_translate("MainWindow", "6.4.12 Расположение земельного участка (в том числе удаленность земельного участка) относительно рекреационных зон (лесной массив, парковая зона, заповедная зона и прочее), ее наименование и тип:"))
        self.label_93.setText(_translate("MainWindow", "6.4.13 Наличие коммуникаций (электроснабжение, газоснабжение, водоснабжение, теплоснабжение, канализация), в том числе удаленность земельного участка:"))
        self.label_89.setText(_translate("MainWindow", "6.5 Характеристики здания, сооружения, в котором расположено помещение, машино-место:"))
        self.label_87.setText(_translate("MainWindow", "6.5.1 Вид объекта недвижимости:"))
        self.label_90.setText(_translate("MainWindow", "6.5.2 Кадастровый номер:"))
        self.label_84.setText(_translate("MainWindow", "6.5.3 Сведения о вхождении здания, сооружения, в состав ЕНК или предприятия как имущественного комплекса (в том числе кадастровый номер):"))
        self.label_83.setText(_translate("MainWindow", "6.5.4 Вид разрешенного использования:"))
        self.label_97.setText(_translate("MainWindow", "6.5.5 Назначение:"))
        self.label_99.setText(_translate("MainWindow", "6.5.6 Наименование:"))
        self.label_98.setText(_translate("MainWindow", "6.5.7 Площадь (здания, помещения, машино-место, сооружение), основная характеристика (сооружения):"))
        self.label_100.setText(_translate("MainWindow", "6.5.8 Количество этажей, в том числе подземных этажей (при наличии этажности у здания или сооружения):"))
        self.label_86.setText(_translate("MainWindow", "6.5.9 Фактическое использование: "))
        self.label_96.setText(_translate("MainWindow", "6.5.10 Материал наружных стен:"))
        self.label_95.setText(_translate("MainWindow", "6.5.11 Год ввода в эксплуатацию здания или сооружения по завершении его строительства либо год завершения строительства таких объектов недвижимости, если в соответствии с федеральным законом \n"
"выдача разрешения на ввод объекта в эксплуатацию не предусматривается для здания или сооружения:"))
        self.label_82.setText(_translate("MainWindow", "6.5.12 Дата окончания проведения капитального ремонта (реконструкции):"))
        self.label_31.setText(_translate("MainWindow", "6.5.13 Наличие коммуникаций (электроснабжение, газоснабжение, водоснабжение, теплоснабжение, канализация), в том числе удаленность земельного участка:"))
        self.label_101.setText(_translate("MainWindow", "6.5.14 Линия застройки:"))
        self.label_102.setText(_translate("MainWindow", "6.6 Иное:"))
        self.pushButton.setText(_translate("MainWindow", "                            Сохранить                              "))

